import os
import json
from groq import Groq

class GeneratorAgent:
    """
    AI Agent 2: Card Generator.
    - Reads the original article text and the analysis report from Agent 1 (Analyzer).
    - Uses Groq LLM to generate exactly 3 sequential insight swipe cards.
    - Incorporates the themes, suggested insights, and style guidelines from Agent 1.
    """

    def run(self, state: dict) -> dict:
        title = state.get("title", "Untitled")
        category = state.get("category", "General")
        text = state.get("extracted_text", "")
        analysis = state.get("analysis_report", {})
        
        print(f"[Agent 2 Generator] Compiling swipe cards for: '{title}' using Agent 1's analysis")
        
        groq_key = os.getenv("GROQ_API_KEY")
        if not groq_key:
            raise Exception("GROQ_API_KEY environment variable is not configured.")
            
        try:
            client = Groq(api_key=groq_key)
            
            # Format Agent 1's report for the prompt
            analysis_str = json.dumps(analysis, indent=2)
            
            prompt = (
                f"You are the Card Generator Agent (Agent 2) in Lumen's publishing pipeline.\n"
                f"Your task is to generate exactly 3 sequential insight cards that summarize the ENTIRE article from start to finish.\n"
                f"You MUST base the summaries on the structural analysis report generated by Agent 1 (Analyzer).\n\n"
                f"Article Title: {title}\n"
                f"Article Category: {category}\n\n"
                f"--- AGENT 1 ANALYSIS REPORT ---\n{analysis_str}\n--------------------------------\n\n"
                f"--- ORIGINAL ARTICLE TEXT ---\n{text}\n-------------------------------\n\n"
                f"INSTRUCTIONS:\n"
                f"1. Generate exactly 3 cards in sequence. Together, they must sequentially cover the entire narrative arc of the article:\n"
                f"   - Card 0 (Introduction): Establish the context, hook, and background of the article.\n"
                f"   - Card 1 (Core Details): Detail the central arguments, events, evidence, or findings.\n"
                f"   - Card 2 (Conclusion): Summarize the final takeaway, future outlook, and broader implications.\n"
                f"2. Incorporate the themes, core arguments, suggested insights, and the language style guide recommended by Agent 1.\n"
                f"3. Each card MUST contain the following JSON keys:\n"
                f"   - \"card_index\": integer (0, 1, or 2)\n"
                f"   - \"category\": string (must match the article category: {category})\n"
                f"   - \"title\": string (a short, highly punchy headline)\n"
                f"   - \"summary\": string (a sweet and comprehensive summary of this part of the story, written in exactly 2 or 3 complete, well-formed, and elegant sentences. Do not write just a single short line. Ensure it captures specific details and depth, keeping the length around 40-60 words.)\n"
                f"4. Output must be a valid JSON array of objects. Do not include markdown codeblocks or conversational text."
            )
            
            completion = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "system", "content": "You are a specialized card generation agent. You only output valid JSON arrays of card objects."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                response_format={"type": "json_object"}
            )
            
            raw_response = completion.choices[0].message.content
            parsed = json.loads(raw_response)
            
            # Standardize parsed object format
            if isinstance(parsed, dict) and "cards" in parsed:
                cards = parsed["cards"]
            elif isinstance(parsed, dict) and len(parsed) == 1 and isinstance(list(parsed.values())[0], list):
                cards = list(parsed.values())[0]
            elif isinstance(parsed, list):
                cards = parsed
            else:
                cards = [parsed]
                
            state["raw_cards"] = cards
            print(f"[Agent 2 Generator] Successfully generated {len(state['raw_cards'])} raw cards.")
            
        except Exception as e:
            print(f"[Agent 2 Generator Error] Failed card generation: {e}")
            raise Exception(f"AI Card Generator Agent API call failed: {str(e)}")
            
        return state
        
    def generate_mock_cards(self, state: dict) -> list:
        title = state.get("title", "Untitled")
        category = state.get("category", "General")
        text = state.get("extracted_text", "")
        
        # Clean clean_title for card headlines
        clean_title = title.replace("Article from ", "").replace("Scraping: ", "").strip()
        for sep in [" - ", " | ", " – "]:
            if sep in clean_title:
                clean_title = clean_title.split(sep)[0].strip()
        clean_title = clean_title.rstrip(".… ")
        
        # Extract sentences from body text
        import re
        raw_sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', text) if len(s.strip()) > 30]
        raw_sentences = [re.sub(r'\s+', ' ', s) for s in raw_sentences]
        
        # Filter out social links, emails, and junk lines
        ignore_keywords = ["got a tip", "send it", "follow us", "@", "copyright", "photo by", "click here", "read more", "subscribe", "newsletter", "twitter", "facebook"]
        sentences = []
        for s in raw_sentences:
            s_lower = s.lower()
            if any(kw in s_lower for kw in ignore_keywords):
                continue
            sentences.append(s)
            
        # Fallbacks if text is too short or empty
        if len(sentences) < 3:
            sentences = [
                f"This dispatch covers the latest updates regarding {clean_title}.",
                "Important structural changes are prompting administrative adaptations across key sectors.",
                "Further analysis will examine how these policies shape overall attention trends."
            ]
            
        # Select 3 sentences representing beginning, middle, and end
        s1 = sentences[0]
        s2 = sentences[len(sentences) // 2]
        s3 = sentences[-1]
        
        # Generate headlines by taking the first 4-5 words of each sentence
        def make_headline(sentence):
            words = [w.strip(".,!?;:\"'()[]") for w in sentence.split() if w]
            # Avoid empty or short words
            words = [w for w in words if len(w) > 2]
            if len(words) >= 3:
                return " ".join(words[:3]).capitalize()
            return "Key takeaway"
            
        return [
            {
                "card_index": 0,
                "category": category,
                "title": make_headline(s1),
                "summary": s1
            },
            {
                "card_index": 1,
                "category": category,
                "title": make_headline(s2),
                "summary": s2
            },
            {
                "card_index": 2,
                "category": category,
                "title": make_headline(s3),
                "summary": s3
            }
        ]
