/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TechStackRouteImport } from './routes/tech-stack'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderArticleIdRouteImport } from './routes/reader.$articleId'
import { Route as CmsWorkRouteImport } from './routes/cms.work'
import { Route as CmsNewRouteImport } from './routes/cms.new'
import { Route as CmsEditArticleIdRouteImport } from './routes/cms.edit.$articleId'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TechStackRoute = TechStackRouteImport.update({
  id: '/tech-stack',
  path: '/tech-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderArticleIdRoute = ReaderArticleIdRouteImport.update({
  id: '/reader/$articleId',
  path: '/reader/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsWorkRoute = CmsWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => CmsRoute,
} as any)
const CmsNewRoute = CmsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CmsRoute,
} as any)
const CmsEditArticleIdRoute = CmsEditArticleIdRouteImport.update({
  id: '/edit/$articleId',
  path: '/edit/$articleId',
  getParentRoute: () => CmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/cms': typeof CmsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/tech-stack': typeof TechStackRoute
  '/trending': typeof TrendingRoute
  '/cms/new': typeof CmsNewRoute
  '/cms/work': typeof CmsWorkRoute
  '/reader/$articleId': typeof ReaderArticleIdRoute
  '/cms/edit/$articleId': typeof CmsEditArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/cms': typeof CmsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/tech-stack': typeof TechStackRoute
  '/trending': typeof TrendingRoute
  '/cms/new': typeof CmsNewRoute
  '/cms/work': typeof CmsWorkRoute
  '/reader/$articleId': typeof ReaderArticleIdRoute
  '/cms/edit/$articleId': typeof CmsEditArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/cms': typeof CmsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/tech-stack': typeof TechStackRoute
  '/trending': typeof TrendingRoute
  '/cms/new': typeof CmsNewRoute
  '/cms/work': typeof CmsWorkRoute
  '/reader/$articleId': typeof ReaderArticleIdRoute
  '/cms/edit/$articleId': typeof CmsEditArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/categories'
    | '/chat'
    | '/cms'
    | '/features'
    | '/feed'
    | '/login'
    | '/privacy'
    | '/register'
    | '/tech-stack'
    | '/trending'
    | '/cms/new'
    | '/cms/work'
    | '/reader/$articleId'
    | '/cms/edit/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/categories'
    | '/chat'
    | '/cms'
    | '/features'
    | '/feed'
    | '/login'
    | '/privacy'
    | '/register'
    | '/tech-stack'
    | '/trending'
    | '/cms/new'
    | '/cms/work'
    | '/reader/$articleId'
    | '/cms/edit/$articleId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/categories'
    | '/chat'
    | '/cms'
    | '/features'
    | '/feed'
    | '/login'
    | '/privacy'
    | '/register'
    | '/tech-stack'
    | '/trending'
    | '/cms/new'
    | '/cms/work'
    | '/reader/$articleId'
    | '/cms/edit/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CategoriesRoute: typeof CategoriesRoute
  ChatRoute: typeof ChatRoute
  CmsRoute: typeof CmsRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TechStackRoute: typeof TechStackRoute
  TrendingRoute: typeof TrendingRoute
  ReaderArticleIdRoute: typeof ReaderArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-stack': {
      id: '/tech-stack'
      path: '/tech-stack'
      fullPath: '/tech-stack'
      preLoaderRoute: typeof TechStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$articleId': {
      id: '/reader/$articleId'
      path: '/reader/$articleId'
      fullPath: '/reader/$articleId'
      preLoaderRoute: typeof ReaderArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/work': {
      id: '/cms/work'
      path: '/work'
      fullPath: '/cms/work'
      preLoaderRoute: typeof CmsWorkRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/new': {
      id: '/cms/new'
      path: '/new'
      fullPath: '/cms/new'
      preLoaderRoute: typeof CmsNewRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/edit/$articleId': {
      id: '/cms/edit/$articleId'
      path: '/edit/$articleId'
      fullPath: '/cms/edit/$articleId'
      preLoaderRoute: typeof CmsEditArticleIdRouteImport
      parentRoute: typeof CmsRoute
    }
  }
}

interface CmsRouteChildren {
  CmsNewRoute: typeof CmsNewRoute
  CmsWorkRoute: typeof CmsWorkRoute
  CmsEditArticleIdRoute: typeof CmsEditArticleIdRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsNewRoute: CmsNewRoute,
  CmsWorkRoute: CmsWorkRoute,
  CmsEditArticleIdRoute: CmsEditArticleIdRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  CategoriesRoute: CategoriesRoute,
  ChatRoute: ChatRoute,
  CmsRoute: CmsRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TechStackRoute: TechStackRoute,
  TrendingRoute: TrendingRoute,
  ReaderArticleIdRoute: ReaderArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
